spring:
  main:
    #允许相同Bean，后者覆盖
    allow-bean-definition-overriding: true
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 120.79.11.148:8848
dubbo:
  application:
    name: dubbo-provider
  protocol:
    name: dubbo
    port: 12345
  registry:
    address: nacos://120.79.11.148:8848
  scan:
      basePackages: com.thappy.dubbo.provider.service


server:
  port: 20201

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: info
    ccom.thappy.dubbo.provider.service: debug
